### PR TITLE
Omit unnecessary repetition of emails

### PR DESCRIPTION
**Pull request by gagansh7171**

### CODE REVIEW

**Review by algomaster99 — COMMENTED** [review]
Looks good to me. In addition to the changes, we can also edit the original emails' configuration to include the examples.
```yml
emails:
  emailsBackend: # django.core.mail.backends.smtp.EmailBackend, or your own backend used for sending emails
  ...
```

**Comment by gagansh7171** [comment]
@algomaster99 I am working on omniport-cli and I am planning to take input for these from the user along with examples just like one gets in `npm init`

**Comment by dhruvkb** [comment]
Omniport CLI 👌

**Comment by algomaster99** [comment]
@gagansh7171 Reword the commit message to `Omit unnecessary repetition of emails`

**Comment by gagansh7171** [comment]
@algomaster99 done

**Comment by algomaster99** [comment]
@gagansh7171 
Screenshot from 2020-11-05 09-40-47
This is not a commit message.


Screenshot from 2020-11-05 09-41-21
This is a commit message.

**Comment by algomaster99** [comment]
@gagansh7171 What is taking so long?

**Comment by algomaster99** [comment]
Closed due to inactivity.

**Pull request closed without merging**
