### PR TITLE
Add notification store to base_stencil.yml

### PR DESCRIPTION
**Pull request by gagansh7171**

### CODE REVIEW

**Review by dhruvkb — APPROVED** [review]
It's cool.

**Review by algomaster99 — APPROVED** [review]

**Comment by algomaster99** [comment]
@ayushjn20 @pradumangoyal If I recall correctly, we renamed `notification_store` to `communication_store`, right? In that case, this PR should be reverted.

**Comment by ayushjn20** [comment]
Yes, `notifications-store` should not exist.

**Comment by algomaster99** [comment]
Cool, I will revert this.

**Pull request merged**
