### PR TITLE
Override semantic UI's CSS for Full Calendar library

### PR DESCRIPTION
**Pull request by SuyashSalampuria**

### CODE REVIEW

**Comment by dhruvkb** [comment]
Why is everything `!important`? Surely there must be a better way to get around this. Also, you should check the **Preview** tab to make sure you're comments are valid Markdown.

image

**Comment by dhruvkb** [comment]
Also I just noticed that this CSS is not for Semantic UI components, so it should be in a different folder.

**Comment by ayushjn20** [comment]
@liquidslr @pradumangoyal @Tushar19varshney Review this ASAP. Provide necessary suggestions.

**Comment by dhruvkb** [comment]
**Do not merge** until 

- https://github.com/IMGIITRoorkee/omniport-backend/pull/59#issuecomment-527164547
- https://github.com/IMGIITRoorkee/omniport-backend/pull/59#issuecomment-527167184

are resolved.

**Pull request closed without merging**
