### PR TITLE
Add a tolerance in application logo apsect ratio of oauth and display picture aspect ratio

### PR DESCRIPTION
**Pull request by pradumangoyal**
Merge once https://github.com/IMGIITRoorkee/omniport-backend-formula-one/pull/2 is merged.

### CODE REVIEW

**Comment by ayushjn20** [comment]
`0.3` seems a large value. Also, _confidence_ is wrongly used in the commit message. It should be _tolerance_. And tolerance usually takes values like `1%`, `5%`, `10%`, and 30% seems quite high.

**Comment by pradumangoyal** [comment]
I did 0.1 (10%) in the display picture, in the logo section, I added a considerable confidence value in the application model as I thought that a logo couldn't be expected a perfect square. We can revert it for small errors though.

**Comment by dhruvkb** [comment]
If the aspect ratio cannot be guaranteed as with the case of the application logos, it would be better to remove the validation rather than have a tolerance that practically allows a rectangle to pass through. 1.3:1 ≈ 4:3 which used to be the resolution of monitors back in the day (pretty rectangular imo).

**Comment by pradumangoyal** [comment]
I have updated both values to 0.05. Let the application logo remain square only, those with a rectangular logo may make it square by apt padding.

**Pull request merged**
