### PR TITLE
[IMPORTANT] Account migration Request

### PR DESCRIPTION
**Pull request by nanuclickity**
Hello IMG,

Sub - Need my account migrated in newchanneli.

I am 2013 batch student, was not able to complete my no-dues during my time there.
Had to leave for a job due to financial reasons at the time.
I have never been able to come back to roorkee due to professional limitations.
However, I need my degree for my future endeavours.

Recently, I learnt that I can file my nodues through newchanneli.
However, I am not able to login. It says my account does not exist.
But I am able to login on old channeli.

I've tried contacting the offices and academic section. But no one picks up the phone or replies to email.
Please consider my hopeful attempt by raising a PR.

Tushar Kant
09111042
B.Tech Biotechnology
me@tushar.works
9627446918

### CODE REVIEW

**Comment by nanuclickity** [comment]
@dhruvkb @rish9101 @pradumangoyal

**Comment by dhruvkb** [comment]
This is new. We generally receive these requests on email.

**Comment by nanuclickity** [comment]
@dhruvkb Desperate times. Desperate Measures. 🙃 

Please help me initiate the communication with the correct person.
Also, please let me know if there are any steps I need to take.

**Comment by dhruvkb** [comment]
You've already tagged the right people. But @algomaster99 and @Ajayneethikannan could help. Do send an email to `img@iitr.ac.in` though.

**Comment by nanuclickity** [comment]
Thanks @dhruvkb 
I did send an email on 19th Sep. Have replied on it to again to make it stand out.

**Comment by pradumangoyal** [comment]
Hey @nanuclickity. You must have received a mail containing all the required information. You may need to access your old Gmail id for resetting your password.

**Comment by nanuclickity** [comment]
@pradumangoyal Thank you so much.  ☺️ 
Have received the email. Started the no-dues process already

**Pull request closed without merging**
